[package]
name = "my_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxy = {path = "../../roxy"}
tracing = "0.1"
tracing-subscriber = "0.3"
config = "0.13"
serde = "1.0"
anyhow = "1.0"
